# Generated by Django 3.2.3 on 2021-05-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_paragr_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragr',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
